name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: |
        echo "Installing Heroku CLI"
        npm install -g heroku
        echo "Logging into Heroku"
        echo $HEROKU_API_KEY | heroku auth:token
        echo "Setting remote for Heroku"
        heroku git:remote -a deepl-proxy
        echo "Pushing to Heroku"
        git push heroku main
